# Generated by Django 4.2.7 on 2025-05-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Printer', 'Printer'), ('Other', 'Other')], max_length=20)),
                ('region', models.CharField(choices=[('North', 'North'), ('South', 'South'), ('Central', 'Central')], max_length=20)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('aims_tag', models.CharField(max_length=50, unique=True)),
                ('lcd_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('lcd_model', models.CharField(blank=True, max_length=50, null=True)),
                ('lcd_serial', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('lcd_aims_tag', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cpu_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_serial', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cpu_aims_tag', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.employee')),
            ],
        ),
    ]
