# Generated by Django 4.2.7 on 2025-05-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_number', models.CharField(max_length=20, unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('region', models.CharField(choices=[('North', 'North'), ('South', 'South'), ('Central', 'Central')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cell_phone', models.CharField(max_length=20)),
                ('city', models.CharField(choices=[('Karachi', 'Karachi'), ('Hyderabad', 'Hyderabad'), ('Sukkur', 'Sukkur'), ('NawabShah', 'NawabShah'), ('Larkana', 'Larkana'), ('Islamabad', 'Islamabad'), ('Lahore', 'Lahore'), ('Multan', 'Multan'), ('Sialkot', 'Sialkot'), ('Rawalpindi', 'Rawalpindi')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date_joined', models.DateField()),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
