# Generated by Django 4.2.16 on 2025-05-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosteIOConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(blank=True, help_text='Poste.io admin API token', max_length=100)),
                ('domain', models.CharField(default='itsupportserver.internal', max_length=100)),
                ('smtp_host', models.CharField(default='mail.itsupportserver.internal', max_length=100)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=100)),
                ('smtp_password', models.CharField(blank=True, max_length=100)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('imap_host', models.CharField(default='mail.itsupportserver.internal', max_length=100)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_username', models.CharField(blank=True, max_length=100)),
                ('imap_password', models.CharField(blank=True, max_length=100)),
                ('default_from_email', models.EmailField(default='no-reply@itsupportserver.internal', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
