# Generated by Django 4.2.16 on 2025-05-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorescalation_management', '0001_initial'),
        ('custom_email_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='email_attachments/')),
                ('size_mb', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='EmailRelayConfig',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendorescalation_management.vendorescalationmanagement'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='custom_email_client.emailmessage'),
        ),
    ]
