# Generated by Django 4.2.20 on 2025-05-10 10:04

from django.db import migrations, models
import file_attachment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('file_data', models.BinaryField(validators=[file_attachment.models.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
