# Generated by Django 4.2.20 on 2025-05-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_attachment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='app_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='record_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
