# Generated by Django 4.2.20 on 2025-05-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0001_initial'),
        ('file_attachment', '0002_attachment_app_name_attachment_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='record_id',
        ),
        migrations.AddField(
            model_name='attachment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.employee', to_field='emp_number'),
        ),
    ]
