# Generated by Django 4.2.20 on 2025-05-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_attachment', '0003_remove_attachment_app_name_and_more'),
    ]

    operations = [
    ]
