# Generated by Django 4.2.20 on 2025-05-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_attachment', '0004_auto_20250510_1730'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('filename', 'employee'), name='unique_attachment'),
        ),
    ]
