# Generated by Django 4.2.20 on 2025-05-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netbios_name', models.CharField(blank=True, max_length=255)),
                ('ipv4_address', models.CharField(blank=True, max_length=15)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('hardware_details', models.JSONField()),
                ('software_details', models.JSONField()),
            ],
            options={
                'ordering': ['-scan_time'],
            },
        ),
    ]
