# Generated by Django 4.2.20 on 2025-05-15 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('employee_management', 'Employee Management'), ('asset_management', 'Asset Management'), ('warehouse_management', 'Warehouse Management'), ('vendorescalation_management', 'Vendor Escalation Management'), ('report_generation', 'Report Generation'), ('search', 'Search'), ('user_activity', 'User Activity'), ('file_management', 'File Management'), ('scan_hardware', 'Scan Hardware'), ('live', 'Live'), ('two_factor_auth', 'Two Factor Auth')], max_length=50)),
                ('permission_level', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'app_name')},
            },
        ),
    ]
