# Generated by Django 4.2.20 on 2025-05-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppermission',
            name='app_name',
            field=models.CharField(choices=[('administration_management', 'Administration Management'), ('employee_management', 'Employee Management'), ('asset_management', 'Asset Management'), ('warehouse_management', 'Warehouse Management'), ('vendorescalation_management', 'Vendor Escalation Management'), ('report_generation', 'Report Generation'), ('search', 'Search'), ('user_activity', 'User Activity'), ('file_management', 'File Management'), ('scan_hardware', 'Scan Hardware'), ('live', 'Live'), ('two_factor_auth', 'Two Factor Auth')], max_length=50),
        ),
    ]
