# Generated by Django 4.2.16 on 2025-05-18 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration_management', '0002_alter_apppermission_app_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apppermission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='apppermission',
            name='app_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_posteio_email', models.BooleanField(default=False, help_text='Create Poste.io email account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
