# Generated by Django 4.2.7 on 2025-05-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorEscalationManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('device_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Printer', 'Printer'), ('Other', 'Other')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('aims_tag', models.CharField(blank=True, max_length=50)),
                ('lcd_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('lcd_model', models.CharField(blank=True, max_length=50, null=True)),
                ('lcd_serial', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('lcd_aims_tag', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cpu_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_serial', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cpu_aims_tag', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('issue_details', models.TextField()),
                ('poc_name', models.CharField(max_length=100)),
                ('it_email', models.EmailField(max_length=254)),
                ('poc_cell', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('closure_remarks', models.TextField(blank=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management.employee')),
            ],
        ),
    ]
